#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Embedded Stack Usage & Maximum Call Chain Analyzer (Dual-Toolchain: GCC & Keil)
Computes Worst-Case Stack Depth (WCET Stack), Interrupt Nesting, and flags local stack bloat.
"""

import os
import sys
import json
import argparse
import re
import glob
import subprocess
import shutil
from pathlib import Path
from collections import defaultdict

# Ensure UTF-8 output on Windows
if sys.platform == 'win32':
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
        sys.stderr.reconfigure(encoding='utf-8', errors='replace')
    except AttributeError:
        pass


def find_objdump_binary():
    """Locate arm-none-eabi-objdump or llvm-objdump binary."""
    which_path = shutil.which("arm-none-eabi-objdump")
    if which_path:
        return which_path
        
    candidates = [
        Path(r"C:\Program Files (x86)\GNU Arm Embedded Toolchain\bin\arm-none-eabi-objdump.exe"),
        Path(r"C:\Program Files\GNU Arm Embedded Toolchain\bin\arm-none-eabi-objdump.exe"),
    ]
    for c in candidates:
        if c.is_file():
            return str(c)
    return None


# ==============================================================================
# 1. GCC Stack & Callgraph Analysis Engine (.su + objdump -d)
# ==============================================================================

def parse_gcc_su_files(search_dir):
    """Parse all .su files generated by gcc -fstack-usage."""
    func_stack = {}
    su_files = []
    for root, _, files in os.walk(search_dir):
        for f in files:
            if f.endswith(".su"):
                su_files.append(os.path.join(root, f))
    
    for sf in su_files:
        try:
            with open(sf, "r", encoding="utf-8", errors="ignore") as f:
                for line in f:
                    parts = line.strip().split("\t")
                    if len(parts) >= 2:
                        loc_part = parts[0]
                        stack_bytes = int(parts[1])
                        qualifier = parts[2] if len(parts) > 2 else "static"
                        
                        # Format: ./code/app/sys.c:21:6:sys_run
                        loc_tokens = loc_part.split(":")
                        if len(loc_tokens) >= 4:
                            fpath = loc_tokens[0]
                            line_no = int(loc_tokens[1])
                            col_no = int(loc_tokens[2])
                            func_name = loc_tokens[3]
                        else:
                            fpath = "unknown"
                            line_no = 0
                            func_name = loc_tokens[-1]
                            
                        func_stack[func_name] = {
                            "stack_bytes": stack_bytes,
                            "file": fpath.replace("\\", "/"),
                            "line": line_no,
                            "type": qualifier
                        }
        except Exception:
            pass
            
    return func_stack, len(su_files)


def extract_callgraph_from_elf(elf_path, objdump_bin=None):
    """Extract caller -> callee callgraph from ELF disassembly."""
    if not objdump_bin or not os.path.isfile(objdump_bin):
        objdump_bin = find_objdump_binary()
        
    if not objdump_bin:
        return {"error": "arm-none-eabi-objdump not found. Cannot construct callgraph."}
        
    try:
        proc = subprocess.run(
            [objdump_bin, "-d", elf_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
            errors="ignore"
        )
        disasm = proc.stdout
    except Exception as e:
        return {"error": f"Failed to run objdump: {str(e)}"}
        
    call_graph = defaultdict(set)
    func_addrs = {}
    current_func = None
    
    func_header_re = re.compile(r"^([0-9a-fA-F]+)\s+<([^>]+)>:")
    bl_re = re.compile(r"\bbl(?:x)?(?:\.w)?\s+[0-9a-fA-F]+\s+<([^>+]+)")
    
    for line in disasm.splitlines():
        m_func = func_header_re.match(line)
        if m_func:
            current_func = m_func.group(2)
            func_addrs[current_func] = int(m_func.group(1), 16)
            if current_func not in call_graph:
                call_graph[current_func] = set()
            continue
        if current_func:
            m_bl = bl_re.search(line)
            if m_bl:
                callee = m_bl.group(1)
                call_graph[current_func].add(callee)
                
    # Convert sets to sorted lists for deterministic output
    return {
        "call_graph": {k: sorted(v) for k, v in call_graph.items()},
        "func_addrs": func_addrs
    }


def compute_max_call_chain(root_func, call_graph, func_stack, memo=None, visited=None):
    """Compute maximum call chain and stack depth from a root function using DFS."""
    if memo is None:
        memo = {}
    if visited is None:
        visited = set()
        
    if root_func in memo:
        return memo[root_func]
        
    if root_func in visited:
        # Recursion cycle detected
        return (0, [root_func + " (Recursive/Loop)"])
        
    visited.add(root_func)
    
    # Self stack size
    self_cost = func_stack.get(root_func, {}).get("stack_bytes", 0)
    
    callees = call_graph.get(root_func, [])
    if not callees:
        res = (self_cost, [root_func])
    else:
        max_sub_cost = 0
        best_sub_path = []
        for c in callees:
            sub_cost, sub_path = compute_max_call_chain(c, call_graph, func_stack, memo, visited)
            if sub_cost > max_sub_cost:
                max_sub_cost = sub_cost
                best_sub_path = sub_path
                
        res = (self_cost + max_sub_cost, [root_func] + best_sub_path)
        
    visited.remove(root_func)
    memo[root_func] = res
    return res


def analyze_gcc_stack(search_dir, elf_path=None, reserved_stack_bytes=8192):
    """Full GCC stack and call chain analysis."""
    func_stack, su_count = parse_gcc_su_files(search_dir)
    
    if not func_stack:
        return {
            "error": "No .su stack usage files found.",
            "hint": "Add '-fstack-usage' to GCC CFLAGS and recompile."
        }
        
    callgraph_data = extract_callgraph_from_elf(elf_path) if elf_path else {}
    call_graph = callgraph_data.get("call_graph", {})
    
    # Identify entry points: main/Reset_Handler and ISRs
    isrs = []
    main_entries = []
    for f in call_graph.keys():
        lower_f = f.lower()
        if f in ['main', 'Reset_Handler', '_start']:
            main_entries.append(f)
        elif lower_f.endswith('_irqhandler') or lower_f.endswith('_handler'):
            if f not in ['Default_Handler', 'main']:
                isrs.append(f)
                
    if not main_entries and 'main' in func_stack:
        main_entries = ['main']
        
    primary_main = 'main' if 'main' in call_graph else (main_entries[0] if main_entries else None)
    
    # Compute Main call chain
    memo = {}
    main_chain_info = {"depth_bytes": 0, "path": []}
    if primary_main:
        cost, path = compute_max_call_chain(primary_main, call_graph, func_stack, memo)
        main_chain_info = {
            "entry": primary_main,
            "depth_bytes": cost,
            "path": path,
            "path_details": [
                {"name": p, "stack": func_stack.get(p, {}).get("stack_bytes", 0)} for p in path
            ]
        }
        
    # Compute ISR call chains
    isr_results = []
    max_isr_depth = 0
    worst_isr = None
    
    for isr in isrs:
        cost, path = compute_max_call_chain(isr, call_graph, func_stack, memo)
        isr_entry = {
            "isr": isr,
            "depth_bytes": cost,
            "path": path
        }
        isr_results.append(isr_entry)
        if cost > max_isr_depth:
            max_isr_depth = cost
            worst_isr = isr_entry
            
    isr_results.sort(key=lambda x: x["depth_bytes"], reverse=True)
    
    # Cortex-M automatic stack frame (8 words = 32 bytes) on interrupt entry
    cortex_m_irq_overhead = 32
    
    # Worst-Case Stack Depth (Main thread + Highest ISR + IRQ overhead)
    worst_case_total = main_chain_info["depth_bytes"] + max_isr_depth + (cortex_m_irq_overhead if max_isr_depth > 0 else 0)
    
    # Top stack consumers (individual functions)
    top_stack_funcs = sorted(
        [{"name": k, "stack_bytes": v["stack_bytes"], "file": v["file"], "line": v["line"]} for k, v in func_stack.items()],
        key=lambda x: x["stack_bytes"],
        reverse=True
    )
    
    # Filter dangerous functions (> 128 bytes on stack)
    high_risk_locals = [f for f in top_stack_funcs if f["stack_bytes"] >= 128]
    
    # Headroom calculation
    margin_bytes = reserved_stack_bytes - worst_case_total
    margin_percent = round((margin_bytes / reserved_stack_bytes) * 100, 1) if reserved_stack_bytes > 0 else 0
    
    if margin_bytes < 0:
        safety_status = "CRITICAL_OVERFLOW"
    elif margin_percent < 20:
        safety_status = "WARNING_LOW_HEADROOM"
    else:
        safety_status = "SAFE"
        
    return {
        "toolchain": "GCC (GNU Arm Embedded)",
        "summary": {
            "total_functions_analyzed": len(func_stack),
            "su_files_parsed": su_count,
            "reserved_stack_bytes": reserved_stack_bytes,
            "worst_case_stack_bytes": worst_case_total,
            "stack_margin_bytes": margin_bytes,
            "stack_margin_percent": margin_percent,
            "safety_status": safety_status
        },
        "main_call_chain": main_chain_info,
        "worst_isr": worst_isr,
        "top_isrs": isr_results[:8],
        "top_stack_eating_functions": top_stack_funcs[:15],
        "high_risk_stack_functions": high_risk_locals
    }


# ==============================================================================
# 2. Keil Callgraph Analysis Engine (*.htm)
# ==============================================================================

def parse_keil_callgraph_htm(htm_path, reserved_stack_bytes=8192):
    """Parse Keil armlink HTML static callgraph report."""
    if not os.path.isfile(htm_path):
        return {"error": f"Keil callgraph file not found: {htm_path}"}
        
    try:
        with open(htm_path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()
    except Exception as e:
        return {"error": f"Failed to read Keil HTML report: {str(e)}"}
        
    # Match Maximum Stack Usage header
    # e.g.: Maximum Stack Usage = 1420 bytes + Unknown(Functions with no stack usage info)
    max_stack_re = re.compile(r'Maximum Stack Usage\s*=\s*(\d+)\s*bytes', re.IGNORECASE)
    call_chain_re = re.compile(r'Call chain\s*=\s*([^\n<]+)', re.IGNORECASE)
    
    m_stack = max_stack_re.search(content)
    m_chain = call_chain_re.search(content)
    
    max_stack_bytes = int(m_stack.group(1)) if m_stack else 0
    call_chain_str = m_chain.group(1).replace("&rArr;", "->").strip() if m_chain else "Unknown"
    
    # Parse individual functions
    # e.g.: <P><STRONG><a name="[123]"></a>MyFunc</STRONG> (Thumb, 128 bytes, Stack size 32 bytes, file.o)
    func_block_re = re.compile(
        r'<P><STRONG><a\s+name="\[\w+\]"></a>([^<]+)</STRONG>\s*\([^,]+,\s*([0-9]+)\s*bytes,\s*Stack size\s*([0-9]+)\s*bytes,\s*([^)]+)\)',
        re.MULTILINE
    )
    
    functions = []
    for m in func_block_re.finditer(content):
        fn_name = m.group(1)
        code_sz = int(m.group(2))
        stk_sz = int(m.group(3))
        obj_f = m.group(4)
        
        functions.append({
            "name": fn_name,
            "stack_bytes": stk_sz,
            "code_bytes": code_sz,
            "file": obj_f
        })
        
    functions.sort(key=lambda x: x["stack_bytes"], reverse=True)
    high_risk = [f for f in functions if f["stack_bytes"] >= 128]
    
    margin_bytes = reserved_stack_bytes - max_stack_bytes
    margin_percent = round((margin_bytes / reserved_stack_bytes) * 100, 1) if reserved_stack_bytes > 0 else 0
    
    if margin_bytes < 0:
        safety_status = "CRITICAL_OVERFLOW"
    elif margin_percent < 20:
        safety_status = "WARNING_LOW_HEADROOM"
    else:
        safety_status = "SAFE"
        
    return {
        "toolchain": "Keil (ARMCC / Armclang)",
        "summary": {
            "report_file": os.path.basename(htm_path),
            "total_functions_analyzed": len(functions),
            "reserved_stack_bytes": reserved_stack_bytes,
            "worst_case_stack_bytes": max_stack_bytes,
            "stack_margin_bytes": margin_bytes,
            "stack_margin_percent": margin_percent,
            "safety_status": safety_status
        },
        "keil_call_chain": call_chain_str,
        "top_stack_eating_functions": functions[:15],
        "high_risk_stack_functions": high_risk
    }


# ==============================================================================
# 3. Unified Auto-Detection & Report Formatting
# ==============================================================================

def auto_analyze_stack(workspace_dir, elf_path=None, reserved_stack_bytes=8192):
    """Auto-detect whether GCC or Keil was used and run the appropriate analyzer."""
    htm_candidates = []
    su_files = []
    for root, _, files in os.walk(workspace_dir):
        for f in files:
            lower_f = f.lower()
            if lower_f.endswith(".htm") and ("callgraph" in lower_f or "build" in lower_f or lower_f.endswith(".htm")):
                htm_candidates.append(os.path.join(root, f))
            elif lower_f.endswith(".su"):
                su_files.append(os.path.join(root, f))
                
    if htm_candidates:
        return parse_keil_callgraph_htm(htm_candidates[0], reserved_stack_bytes)
        
    if su_files:
        return analyze_gcc_stack(workspace_dir, elf_path, reserved_stack_bytes)
        
    return {
        "error": "No stack analysis data found (neither GCC .su files nor Keil .htm callgraph).",
        "hint": "For GCC, compile with '-fstack-usage'. For Keil, enable '--callgraph' in linker options."
    }


try:
    from embedded_ocr_common import (
        resolve_changed_scope, is_file_or_line_touched,
        build_gate_verdict, format_ai_heal_instruction
    )
except ImportError:
    script_dir = Path(__file__).resolve().parent
    sys.path.insert(0, str(script_dir))
    from embedded_ocr_common import (
        resolve_changed_scope, is_file_or_line_touched,
        build_gate_verdict, format_ai_heal_instruction
    )


def evaluate_stack_gate(result, scope):
    """Filter stack findings against touched scope and evaluate gate verdict."""
    if "error" in result:
        return
        
    high_risk = result.get("high_risk_stack_functions", [])
    new_blockers = []
    legacy_suppressed = []
    ai_heal_instructions = []
    
    for f in high_risk:
        is_touched = is_file_or_line_touched(f.get("file"), f.get("line"), scope)
        if is_touched:
            new_blockers.append(f)
            ai_heal_instructions.append(format_ai_heal_instruction(
                "OVERSIZED_STACK_FRAME",
                f.get("file"),
                f.get("line"),
                f"Function '{f['name']}' allocates {f['stack_bytes']} bytes in its stack frame (threshold: 128 B).",
                "REFACTOR_STACK_ARRAY_TO_STATIC",
                f"In MCU firmware, stack memory is strictly bounded. Function '{f['name']}' allocates {f['stack_bytes']} bytes. Convert large local arrays into 'static' variables or pass a caller-allocated buffer to prevent stack collision."
            ))
        else:
            legacy_suppressed.append(f)
            
    # Check architectural exception: Global worst-case stack collision
    summ = result.get("summary", {})
    arch_hazards = []
    if summ.get("safety_status") == "CRITICAL_OVERFLOW":
        arch_hazards.append({
            "type": "STACK_OVERFLOW_COLLISION",
            "message": f"Global worst-case call stack ({summ.get('worst_case_stack_bytes')} B) exceeds reserved stack ({summ.get('reserved_stack_bytes')} B)!"
        })
        
    gate = build_gate_verdict(new_blockers, [], legacy_suppressed, arch_hazards, scope)
    result["gate"] = gate
    result["new_high_risk_functions"] = new_blockers
    result["legacy_suppressed_functions"] = legacy_suppressed
    result["ai_heal_instructions"] = ai_heal_instructions


def format_markdown_report(result):
    """Format stack analysis results into actionable Markdown."""
    lines = []
    lines.append("# 嵌入式固件最大调用栈与栈溢出安全深度报告\n")
    
    if "error" in result:
        lines.append(f"> [!WARNING]\n> {result['error']}")
        if "hint" in result:
            lines.append(f"> *建议*: {result['hint']}")
        return "\n".join(lines)
        
    gate = result.get("gate", {})
    verdict = gate.get("verdict", "PASSED")
    if verdict == "BLOCKED":
        lines.append(f"> [!CAUTION]\n> **🚨 嵌入式 AI 栈质量门禁拦截 (BLOCKED)**: {gate.get('summary', '')}\n")
    elif verdict == "ARCHITECTURAL_HAZARD":
        lines.append(f"> [!CAUTION]\n> **💥 架构级崩溃警报 (ARCHITECTURAL_HAZARD)**: 最坏调用栈已击穿预留空间！\n")
    else:
        lines.append(f"> [!NOTE]\n> **✅ 嵌入式 AI 栈质量门禁通过 (PASSED)**: {gate.get('summary', '')}\n")
        
    summ = result["summary"]
    toolchain = result.get("toolchain", "Unknown")
    
    lines.append(f"## 1. 栈安全核心指标 ({toolchain})")
    lines.append(f"- **门禁判定结果**: **`{verdict}`** (Exit code: `{gate.get('exit_code', 0)}`)")
    lines.append(f"- **链接器预留栈空间**: `{summ['reserved_stack_bytes']:,}` 字节 ({summ['reserved_stack_bytes']/1024.0:.2f} KB)")
    lines.append(f"- **最坏情况最大栈深 (Worst-Case)**: **`{summ['worst_case_stack_bytes']:,}`** 字节 ({summ['worst_case_stack_bytes']/1024.0:.2f} KB)")
    lines.append(f"- **安全裕量**: `{summ['stack_margin_bytes']}` 字节 (**`{summ['stack_margin_percent']}%`**)")
    if gate.get("is_incremental"):
        lines.append(f"- **🛡️ 老代码历史大栈帧静默**: `{len(result.get('legacy_suppressed_functions', []))}` 个函数")
    
    # High risk functions in newly touched code
    new_high_risk = result.get("new_high_risk_functions", [])
    if new_high_risk:
        lines.append("\n## 2. 🚨 本次修改新增超大局部变量警告 (Single Frame >= 128 Bytes)")
        lines.append("> [!IMPORTANT]\n> 以下函数在 AI 新增/修改的代码中分配了巨大局部变量，是导致栈深暴增的根本原因，必须立即重构！\n")
        lines.append("| 函数名称 | 栈帧占用 (Stack Size) | 危险评级 | 所在源文件位置 | 优化建议 |")
        lines.append("| :--- | :--- | :--- | :--- | :--- |")
        for f in new_high_risk:
            sz = f["stack_bytes"]
            rating = "🚨 极高危 (KB级)" if sz >= 1024 else "⚠️ 中高危"
            loc = f"{os.path.basename(f['file'])}:{f.get('line', '')}" if f.get("file") else "Unknown"
            lines.append(f"| `{f['name']}` | **`{sz} B`** ({sz/1024.0:.2f} KB) | {rating} | `{loc}` | 将大数组改为 static 全局分配 |")
            
        if result.get("ai_heal_instructions"):
            lines.append("\n### 🤖 AI 自愈修复指令清单:")
            for h in result["ai_heal_instructions"]:
                lines.append(f"- **`{h['file']}:{h['line']}`** [{h['action']}]: {h['instruction']}")
    else:
        lines.append("\n## 2. 新增大局部变量检查")
        lines.append("> [!NOTE]\n> ✅ 本次改动未引入单级超过 128 字节的超大栈帧。\n")
        
    # Call chain
    if "main_call_chain" in result and result["main_call_chain"].get("path"):
        mc = result["main_call_chain"]
        lines.append("## 3. 主线程最大调用链 (Deepest Call Path)")
        lines.append(f"- **主调用链累计栈开销**: `{mc['depth_bytes']}` 字节")
        chain_str = " -> ".join([f"`{p}`" for p in mc["path"]])
        lines.append(f"  {chain_str}\n")
        
    if "keil_call_chain" in result:
        lines.append("## 3. Keil 原生计算最大调用链 (Call Chain)")
        lines.append(f"`{result['keil_call_chain']}`\n")
        
    return "\n".join(lines)


def save_dual_reports(output_dir, base_name, md_content, json_data, custom_output=None, no_save=False):
    """
    Save both human-readable Markdown (.md) and machine-readable JSON (.json) reports.
    """
    if no_save:
        return None, None
    if custom_output:
        p = Path(custom_output)
        parent_dir = p.parent
        stem = p.stem
        parent_dir.mkdir(parents=True, exist_ok=True)
        md_path = parent_dir / f"{stem}.md"
        json_path = parent_dir / f"{stem}.json"
    else:
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        md_path = out_dir / f"{base_name}.md"
        json_path = out_dir / f"{base_name}.json"
        
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_content)
        
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(json_data, f, indent=2, ensure_ascii=False)
        
    sys.stderr.write(f"\n[Dual Output Generated]\n  ├─ Markdown (Human): {md_path}\n  └─ JSON (AI):        {json_path}\n\n")
    return str(md_path), str(json_path)


def main():
    parser = argparse.ArgumentParser(description="Embedded Stack Usage & Call Graph Analyzer")
    parser.add_argument("--workspace", "-w", default=".", help="Workspace root directory")
    parser.add_argument("--elf", help="Path to ELF binary")
    parser.add_argument("--htm", help="Path to Keil .htm callgraph file")
    parser.add_argument("--stack-size", type=int, default=8192, help="Reserved stack size in bytes (default: 8192)")
    parser.add_argument("--changed-files", nargs="*", help="Files modified by AI/current commit")
    parser.add_argument("--diff", nargs="?", const="HEAD", help="Use git diff to identify changed scope")
    parser.add_argument("--include-legacy", action="store_true", help="Include legacy technical debt in reports")
    parser.add_argument("--gate", action="store_true", help="Enforce quality gate exit code (1 on blocker, 2 on arch hazard)")
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown", help="Console output format")
    parser.add_argument("--output-dir", help="Directory to save reports (default: <workspace>/reports)")
    parser.add_argument("--output", "-o", help="Custom output path or prefix")
    parser.add_argument("--no-save", action="store_true", help="Do not save reports to disk")
    
    args = parser.parse_args()
    workspace = os.path.abspath(args.workspace)
    
    scope = resolve_changed_scope(workspace, changed_files=args.changed_files, diff_ref=args.diff, include_legacy=args.include_legacy)
    
    if args.htm:
        res = parse_keil_callgraph_htm(args.htm, args.stack_size)
    else:
        res = auto_analyze_stack(workspace, args.elf, args.stack_size)
        
    evaluate_stack_gate(res, scope)
    
    md_report = format_markdown_report(res)
    reports_dir = args.output_dir or os.path.join(workspace, "reports")
    save_dual_reports(reports_dir, "report_stack", md_report, res, args.output, args.no_save)
    
    if args.format == "json":
        print(json.dumps(res, indent=2, ensure_ascii=False))
    else:
        print(md_report)
        
    if args.gate and "gate" in res:
        exit_code = res["gate"].get("exit_code", 0)
        if exit_code != 0:
            sys.exit(exit_code)


if __name__ == "__main__":
    main()
